### ISSUE TITLE
Version 2.0.16.51 -  error opening module preferences

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#103]
Till version 2.0.16.50 I had no problem with opening the module preferences, but in version 2.0.16.51 I get this error:
![afbeelding](https://user-images.githubusercontent.com/46184729/133299311-86e652d4-53b6-4596-8462-2115c47c119a.png)

**Comment by hartenthaler** [comment]
This is a bug that resulted from removing the autoload function. It is fixed now.
