### ISSUE TITLE
White Page after Update

### ISSUE THREAD

**Issue by ChrisSka** [hartenthaler/hh_extended_family#113]
Hello, the module is really great.

Unfortunately, since today's update I only get a white page displayed.

I have to deactivate the module via FTP to be able to access webtrees at all.

**Comment by hartenthaler** [comment]
This can happen if you have not copied all files. Please delete all files in the module directory at your server and upload them again. Do you still get a white page? Try to open your webtrees home page first, maybe you were logged out and there is a security conflict.

**Comment by hartenthaler** [comment]
ok, I'm closing this issue and open another one
