### ISSUE TITLE
Rural theme and wrong position of parameter labels of family parts

### ISSUE THREAD

**Issue by hartenthaler** [hartenthaler/hh_extended_family#116]
I don't know why it worked now.
Now I have deleted the entire folder (hh_extended_family) and uploaded it again.

Before, I had only uploaded and overwritten, and it had always worked.
Then I deleted the folder content and uploaded it again.
The white page always appeared.
But it never occurred to me to delete the folder completely.
The solution can be so simple.

Now I only have a small beauty problem in the design.
After the last entry, the parameters go out of the frame.
I use the Rural-Theme
https://github.com/jon48/webtrees-theme-rural
It doesn't bother me, it just looks unattractive.

I'm attaching a screenshot.

![webtrees](https://user-images.githubusercontent.com/68166740/136591701-30a411a2-8620-431f-a918-3d7da6014acb.png)

_Originally posted by @ChrisSka in https://github.com/hartenthaler/hh_extended_family/issues/113#issuecomment-938797725_

**Comment by ChrisSka** [comment]
In between, everything looks good.
The shifted label appears at the bottom of the last entry.

**Comment by hartenthaler** [comment]
The label should be never at that place at the end of the family parts. 

`_In between, everything looks good._ `   Ok, so I close this now. Reopen it when the failure appears again, please.
