### ISSUE TITLE
2.0.16.58 - Untranslated string: 'Biological greatgrandparents'

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#119]
The new family part in version 2.0.16.58 contains an untranslated string:

`Biological greatgrandparents`

![afbeelding](https://user-images.githubusercontent.com/46184729/136686120-e4855e4c-c87f-4854-8766-1f4740322471.png)

**Comment by hartenthaler** [comment]
Typo, will be fixed in next release

**Comment by hartenthaler** [comment]
will be part of next release tomorrow
