### ISSUE TITLE
Stepchildren of children

### ISSUE THREAD

**Issue by heiler** [hartenthaler/hh_extended_family#125]
Hallo Hermann,

I found a problem with Stepchildren of children, see as an example 

https://www.heiler-ahnen.de/webtrees/tree/heiler/individual/I0135/Theodor-Moritz-Heiler#tab-_hh_extended_family_

The listed Stepchildren of children are Biological grandchildren. Theodor Moritz Heiler has a son Theodor Heiler with two partners. Theo's children are all Theodor's Biological grandchildren.

Kind Regards
Jürgen

**Comment by ro-la** [comment]
I am not sure if this is the same bug. I do not want to open a duplicate.

The display of Grandchildren is not correct. 

In the enclosed picture the left column "Biological grandchildren" is correct. The second one "Children of stepchildren" is wrong. 
Bertalan and Mária are the biological children of Pál, and are the parents of the grandchildrens in the left column.
![obrázok_2021-12-22_110132](https://user-images.githubusercontent.com/60657963/147074528-4487595c-928b-4c1e-852c-cc0837faaa31.png)

This occurs on every family (also in simple families with no step/half siblings/children)
The same behavior cann be seen on the page submitted by @jpretired in https://github.com/hartenthaler/hh_extended_family/issues/135

**Comment by ts110228** [comment]
I found the same problem

**Comment by hartenthaler** [comment]
fixed

**Comment by iyoua** [comment]
I have tested and all bugs have been fixed by you. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hermann ***@***.***&gt;; 
发送时间: 2022年6月9日(星期四) 上午9:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hartenthaler/hh_extended_family] Stepchildren of children (Issue #125)





 
Closed #125 as completed.
