### ISSUE TITLE
Partner Chains

### ISSUE THREAD

**Issue by Fa10175** [hartenthaler/hh_extended_family#126]
on this example :
![pb-partner-chain](https://user-images.githubusercontent.com/10681601/139575450-d70b1aed-3759-4e7c-8175-9c75c7455de9.png)

i see 2 male and 1 female (partner)
 but Jean-Michel has been maried to Janine (first) and Catherine (second)
Janine has maried to Jean-Michel (first) and ??? (second)

what means this partner chains?

I think they are an error.
Thanks

**Comment by hartenthaler** [comment]
It is for Catherine, not Jean-Michel. Catherine was married to Jean-Michel (1. male). He was married to Janine, too (1. female beside Catherine). Janine was a partner of ... (2. male), too. So in the chain of Catherine from Jean-Michel up to ... there are 2 male partners (Jean-Michel and ...) and 1 female partner (Janine) (3 in total) So everything is as it should be.

A partner chain is a tree of chains of partners of partners of partners. So this is sidewards instead the directions to the ancestors or descendants.

**Comment by Fa10175** [comment]
Thanks for these explanations 
May be the translation for "partner chain" should be more explicit.
I don't know how to do this. I will try to explain this to people who connect to my tree, if they ask me.
Thanks
