### ISSUE TITLE
Total of all individuals showing in extended family. 

### ISSUE THREAD

**Issue by mrqd9** [hartenthaler/hh_extended_family#130]

**Comment by mrqd9** [comment]
Add a total number of individuals who appears in whole chart , updated with filtered results.

**Comment by hartenthaler** [comment]
Good idea! Thank you.

**Comment by hartenthaler** [comment]
this will be part of next release, tomorrow

**Comment by hartenthaler** [comment]
found a bug, work is still in progress. will come soon.
