### ISSUE TITLE
Error with 2.1.0.1

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#133]
webtrees 2.1.0-alpha.1 , extended_family v 2.1.0.1, error:

Class "Fisharebest\Webtrees\GedcomCode\GedcomCodePedi" not found …/modules_v4/hh_extended_family/src/Factory/Objects/ExtendedFamilySupport.php:242
#0 …/modules_v4/hh_extended_family/src/Factory/Objects/ExtendedFamilySupport.php(226): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport::generatePedigreeLabel()
#1 …/modules_v4/hh_extended_family/ExtendedFamily.php(184): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport::generateChildLabels()
#2 …/modules_v4/hh_extended_family/ExtendedFamilyPersonExists.php(71): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamily->constructProband()
#3 …/modules_v4/hh_extended_family/ExtendedFamilyTabModule.php(115): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyPersonExists->__construct()
#4 …/modules_v4/hh_extended_family/ExtendedFamilyTabModule.php(504): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyTabModule->personExistsInExtendedFamily()
#5 …/resources/views/individual-page-tabs.phtml(18): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyTabModule->isGrayedOut()
#6 …/app/View.php(183): include('...')
#7 …/app/View.php(280): Fisharebest\Webtrees\View->render()
#8 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make()
#9 …/resources/views/individual-page.phtml(48): view()
#10 …/app/View.php(183): include('...')
#11 …/app/View.php(280): Fisharebest\Webtrees\View->render()
#12 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make()
#13 …/app/Http/ViewResponseTrait.php(50): view()
#14 …/app/Http/RequestHandlers/IndividualPage.php(153): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->viewResponse()

**Comment by hartenthaler** [comment]
Thanks for reporting! I had copied 2.1 over an existing 2.0, therefore GedcomCodePedi was still available. You have used a fresh copy, and then this file/class was moved to another class. It will be repaired in the next release.

**Comment by jpretired** [comment]
A question: as this issue is closed, is the fix included in the latest release?

**Comment by hartenthaler** [comment]
Sorry, no. It will be part of the next release 2.0.1.2, but at the moment I'm still working at another point. But you can download one file and replace it: [hh_extended_family/src/Factory/Objects/ExtendedFamilySupport.php](https://github.com/hartenthaler/hh_extended_family/blob/main/src/Factory/Objects/ExtendedFamilySupport.php)
This should work.

**Comment by hartenthaler** [comment]
the function is completely new programmed and fixed; will be part of the next release
