### ISSUE TITLE
Request: add generations indicator to sorting list in control panel

### ISSUE THREAD

**Issue by reteP-riS** [hartenthaler/hh_extended_family#134]
Hermann, I'd like to ask you to add the generations indicator to the module's sorting list in the control panel like you did it in the description of your module. That would ease the sorting process in case one wants to change the sorting order.

great-grandparents // generation +3
grandparents // generation +2
uncles and aunts // generation +1

**Comment by hartenthaler** [comment]
do you like to see it only or do you like to have the generation indicator in an extra column and buttons to sort the list by this value?

**Comment by reteP-riS** [comment]
Thanks for considering this request. For me just the information would be sufficient.

Others might want to reset the list to the default sorting or even sort it by the generation indicator. But that may not work consistently because there are always family parts with the same generation indicator. And sorting additionally by the generation title will work differently for every language.

So I'd keep it simple and just show the information.

**Comment by reteP-riS** [comment]
Thank you!
