### ISSUE TITLE
Doubts about children/stepchildren

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#135]
Please have a look at extended family of a person in my tree:
https://www.jprodina.cz/tree/nase-rodina/individual/I594/Antonin-Prause#tab-_hh_extended_family_

Antonín has 6 children with two different wives.
As to me all these children are **his biological children** whereas the module says 2 of them (with his second wife) are fis stepchildren.
I doubt this is correct.

**Comment by hartenthaler** [comment]
yes there is a bug, see issue #125

**Comment by hartenthaler** [comment]
fixed
