### ISSUE TITLE
Columns disappear in responsive mode/narrow views

### ISSUE THREAD

**Issue by eyolf** [hartenthaler/hh_extended_family#136]
In the sections where the display of data is placed in several columns, only the first column is shown in mobile view or on narrow screens. Would it be possible to shift these down instead when they don't fit side by side?

**Comment by hartenthaler** [comment]
I just tried it on my iPhone using Edge and Safari. It Looks perfect, all blocks are in only one column. Which browser are you using? Can you provide a screenshot, please.

**Comment by eyolf** [comment]
Hm. Apparently, it's a Firefox thing. Damn, why can't they ever get it right... I also noticed that it applies to other modules as well.
Sorry for the noise.
