### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by ro-la** [hartenthaler/hh_extended_family#137]
In the enclosed file you will find a partial translation for Slovak. 
It is based on the 2.1.0.1 version of the module.

The translation is not completed yet, but I am not sure when the next part will be finished :-)

Ladislav

PS I strongly support https://github.com/hartenthaler/hh_extended_family/issues/117 :-)
[slovak_HH.2-1-0-1.txt](https://github.com/hartenthaler/hh_extended_family/files/7764687/slovak_HH.2-1-0-1.txt)

**Comment by hartenthaler** [comment]
Thank you! Your translation will be part of the next release.

#117 is important, but it is not so easy for me to switch to another solution, so I'm sorry, but it will not make it to the next release.
