### ISSUE TITLE
Children into grandchildren bug

### ISSUE THREAD

**Issue by aurbo** [hartenthaler/hh_extended_family#139]
I've seen the problem in section Grandchildren. This section receives data from section Children. It's a bug? Can you fix it?
![изображение](https://user-images.githubusercontent.com/17171921/150668628-ff982b5a-bd26-42d0-bc8e-450535c8dc2d.png)

**Comment by aurbo** [comment]
Oh, sorry about duplication, not seen that. Thanks for your module, it's great! Home and family - first, so "fix" all "bugs" in real life first :)

**Comment by hartenthaler** [comment]
fixed
