### ISSUE TITLE
Extended family with webtrees 2.1?

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#143]
With webtrees 2.1 I enabled the latest Extended family module 2.1.0.1 and got the error:

`Class 'Fisharebest\Webtrees\GedcomCode\GedcomCodePedi' not found …/modules_v4/hh_extended_family/src/Factory/Objects/ExtendedFamilySupport.php:242

#0 …/modules_v4/hh_extended_family/src/Factory/Objects/ExtendedFamilySupport.php(226): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport::generatePedigreeLabel()

#1 …/modules_v4/hh_extended_family/ExtendedFamily.php(184): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilySupport::generateChildLabels()

#2 …/modules_v4/hh_extended_family/ExtendedFamilyPersonExists.php(71): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamily->constructProband()
#3 …/modules_v4/hh_extended_family/ExtendedFamilyTabModule.php(115): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyPersonExists->__construct()
#4 …/modules_v4/hh_extended_family/ExtendedFamilyTabModule.php(504): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyTabModule->personExistsInExtendedFamily()
#5 …/resources/views/individual-page-tabs.phtml(18): Hartenthaler\Webtrees\Module\ExtendedFamily\ExtendedFamilyTabModule->isGrayedOut()`

**Comment by Fa10175** [comment]
Same

**Comment by arbor95** [comment]
+1

**Comment by arbor95** [comment]
When will you make this run with the current version of webtrees?
What can we do to help?

**Comment by rubenixnagios** [comment]
would love to seen back to work with latest webtrees release

**Comment by hartenthaler** [comment]
Thank you for your requests! I will start working on this module later tonight.

**Comment by hartenthaler** [comment]
fixed, will be part of next release
