### ISSUE TITLE
2.1.5.0 - Summary information block issues

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#148]
[1] What's wrong with this part of the Dutch section?

```
            'The extended family of %1$s has one member.' . I18N::PLURAL . 'The extended family of %1$s has %2$d members.'
                => 'De uitgebreide familie van %1$s heeft één lid.' . I18N::PLURAL . 'De uitgebreide familie van %1$s heeft %2$d leden.',
            '(additional members of the partner chains are not counted)'
                => '(extra leden van de partnerketens worden niet meegeteld)',
            'Some of them are member in more than one part of the extended family.'
                => 'Sommigen van hen zijn lid van meer dan één deel van de uitgebreide familie.',

```
Because the first sentence is not translated:
![afbeelding](https://user-images.githubusercontent.com/46184729/172066942-6ea49ca5-5b7f-4cff-948b-0841d4be2587.png)

[2] There is also a dot missing before the last sentence.

**Comment by TheDutchJewel** [comment]
Found it: source string was changed only in German and Russian sections.

**Comment by hartenthaler** [comment]
You are correct regarding PHP versus po/mo. But a first analysis showed me that it would be complicated to change it now. Your issue addressing this is still open.
