### ISSUE TITLE
Czech translation for 2.1.5

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#155]
Please replace the function czechTranslations() for new version 2.1.5 with content of the attached file:
[2.1.5-czechtranslations.txt](https://github.com/hartenthaler/hh_extended_family/files/8856526/2.1.5-czechtranslations.txt)

Thank you, best regards.
EDIT: oops - after posting this issue I noticed that there is new release 2.1.5.1 with "updated translation".

**Comment by hartenthaler** [comment]
There were many updated strings for other languages. The Czech part was already in a very good situation. I will take your input. Thank you! If there are open points, I will come back to you.

**Comment by hartenthaler** [comment]
I transfered all your input. Finally there were two lines duplicated. I delted the first ones and kept the last two ones.
```
            '%s has no %s recorded.' => 'Pro osobu \'%s\' chybí záznamy %s.',
            '%s has no %s, and no %s recorded.' => 'Pro osobu \'%s\' chybí záznamy %s a %s.',
           
            '%s has no %s recorded.' => '%s nemá zaznamenanou skupinu %s.',
            '%s has no %s, and no %s recorded.' => 'Osoba \'%s\' nemá zaznamenané skupiny %s ani skupinu %s.',
```
