### ISSUE TITLE
Filteroptions

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#18]
I saw your question about [showing living people](https://github.com/hartenthaler/hh_extended_family/issues/17).

In addition I think it would a great enhancement if you add a filter as in the General search page with Male/Female/Unknown and Alive/Dead.

**Comment by hartenthaler** [comment]
I do not see in "General search page" any filter Male/Female/Unknown or Alive/Dead. Can you post a screenshot, please?

There is already an issue - as you mentioned - to show living peoples only. Do you like to see only male cousins, uncles and grandfathers?

btw. can you check the singular/plural translations to dutch in the last version, please?

**Comment by TheDutchJewel** [comment]
The filters are only available after you enter something in the search field:
![image](https://user-images.githubusercontent.com/46184729/121219043-9752f780-c883-11eb-821a-f98115fecdf0.png)

**Comment by TheDutchJewel** [comment]
>Do you like to see only male cousins, uncles and grandfathers?

Not always, but a filter option makes it possible to see this if necessary.

>btw. can you check the singular/plural translations to dutch in the last version, please?

Done, Updated language file sent by mail.

**Comment by hartenthaler** [comment]
There is now (next release) a function "filterOption()" which allows to filter individuals (only_dead, only_alive, ...) but I need help to trigger this option by an user interaction like it is done in the "general search" menu. I didn't found the webtrees module which is handling these filters to use it as an example.

**Comment by hartenthaler** [comment]
Filter by gender and dead/alive is now (release 2.0.16.44) working using a selection by admin in control panel. It is intended to replace this with a filter option for users.

**Comment by hartenthaler** [comment]
I found a solution based on the help of #jon48 . It will be part of the next release of this module.

**Comment by TheDutchJewel** [comment]
Thank You!
