### ISSUE TITLE
Grouping of children and grandchildren

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#19]
In the new Grandchildren section I see the text '**Family with x / Family with x and y**'.

![image](https://user-images.githubusercontent.com/46184729/121726433-d636b680-caea-11eb-86ec-c7195896973e.png)

This text is also untranslated.

**Comment by hartenthaler** [comment]
Yes, the grandchildren should be grouped by the families between the proband and his/her spouses.

**Comment by hartenthaler** [comment]
This is still open, but I just replaced "Family with ..." with an empty string.

This is the same for the part with nephews and nieces.

**Comment by hartenthaler** [comment]
Partners of a partner should be grouped together

**Comment by hartenthaler** [comment]
"partner" and "partner of partner" should be counted separately (see #27)

**Comment by hartenthaler** [comment]
fixed for "partners"

**Comment by hartenthaler** [comment]
fixed for "partners" and "parents-in-law" in release 2.0.16.31

**Comment by hartenthaler** [comment]
separate issues for siblings #59 and nephews/nieces #60 generated
