### ISSUE TITLE
2.0.16.14 - default setting control panel

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#20]
The first time I looked in the control panel, everything was set to '**no**' , even though everything was '**on**'.

Can this be set to '**on**' by default?

**Comment by hartenthaler** [comment]
If there is nothing set in the control panel, then the default in the module is "on". So when you open the control panel the first time, then there the default should be on, too.

**Comment by hartenthaler** [comment]
@TheDutchJewel : can you down- and upload three files and test, please?
- module.php
- settings.phtml
- tab.phtml
When you then open the tab for an individual you should see at the end a new line about "nephews and nieces" (up to now there is no code to find nephews and nieces, but you should see this line); when you open the control panel now, the default for nephews and nieces should be now "yes", as you requested in this issue. Please, play with yes and no, it should work now correct.

**Comment by TheDutchJewel** [comment]
After updating the three files, the Extended family tab shows only the text 'No family available', without a new line about 'nephews and nieces'.
It doesn't matter if I refresh the page or log off/on in webtrees.
By default, everything should be on, so this is not correct.

In the control panel are all groups 'on', except the last one (Nephews and Nieces):
![image](https://user-images.githubusercontent.com/46184729/121765526-b08dc980-cb4b-11eb-89f5-3d6511b6a972.png)

After pressing the Save button, nothing changes:  the tab still shows only the text 'No family available' without a new line about 'nephews and nieces'. 

After changing all options to 'on', everything looks fine again, with at the end the line about 'nephews and nieces'.

**Comment by hartenthaler** [comment]
Thanks for testing! This worked as it should. I exchanged the meaning of on/off (or yes/no). So all the parts which are on before were off after updating the files. The new function "Nephews" is not searching after individuals at the moment, so the message "no family available" was correct. It was important that when you open the control panel the first time, now "yes" is the default.

I will add a message in the control panel to make clear what is the meaning of yes and no.
