### ISSUE TITLE
Request: Add parents and childeren to complete the extended family

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#23]
The Extended family includes Grandparents, Grandchildren, Uncles and Aunts, Cousins, Nephews and Nieces.

It would be nice to also add the Parents and Children to complete the overview.

**Comment by hartenthaler** [comment]
There is another tab "Families", where you can see and edit the parents, spouses, and brothers/sisters. It was not my idea to replace this tab. And there is the navigation bar beside the tabs. When you open the tab "Extended family" you can see there at the same time the members of the core family. So everything is there.
If you intend to get a report which can be printed, your suggestion makes sense.

**Comment by TheDutchJewel** [comment]
> If you intend to get a report which can be printed, your suggestion makes sense.

That's exactly what I mean.

**Comment by hartenthaler** [comment]
So we need four new categories:
- parents (own and by marriage) - generation 1
- siblings including step-siblings - generation 0
- spouses including spouses of spouses - generation 0
- children including step-children - generation -1

**Comment by hartenthaler** [comment]
closed with release 2.0.16.17
