### ISSUE TITLE
Initial status after installation of module: all family parts are deactivated

### ISSUE THREAD

**Issue by arbor95** [hartenthaler/hh_extended_family#25]
Hallo Hermann,
ich habe gerade dein Modul hochgeladen.
Der Reiter Großfamilie ist ausgegraut.

Außerdem meldet die Verwaltung:
 Es ist eine Aktualisierung verfügbar.
Großfamilie — 2.0.16.15 — 2.0.16.17

Ich habe aber den aktuellen Stand gerde heruntergeladen.

**Comment by hartenthaler** [comment]
Die aktuelle Version ist 2.0.16.16; kurz bevor ich 2.0.16.17 fertig stellen wollte, habe ich noch einen Fehler gefunden.

Wenn der Reiter ausgegraut ist, dann gibt es zur aktuellen Person keine Familie. Sind in der Modulverwaltung alle Teilfamilien ausgewählt? Bitte probiere es mit einer Person zu der es Eltern und/oder Kinder gibt.
![Screenshot (372)](https://user-images.githubusercontent.com/6324175/121861943-9fcf8600-ccfa-11eb-8b25-647684820e1a.png)

**Comment by arbor95** [comment]
Ein paar screenshots:
![2021-06-14 15_21_30-Window](https://user-images.githubusercontent.com/6124739/121899322-9824d700-cd24-11eb-97e0-74238216c1bb.jpg)
![2021-06-14 15_19_12-Window](https://user-images.githubusercontent.com/6124739/121899329-98bd6d80-cd24-11eb-8adf-f375a44e6c3d.jpg)
![2021-06-14 15_20_40-Window](https://user-images.githubusercontent.com/6124739/121899330-99560400-cd24-11eb-9348-786ad55d3cf2.jpg)

**Comment by arbor95** [comment]
mit dem close habe ich mich natürlich verklickt. Ansonsten kannst du dir das auch unter
https://freris.de/tree/frese/individual/XI37/Theresia-Limberg
anschauen

**Comment by arbor95** [comment]
Ist wohl ausgegraut, wenn alle Schalter auf "ja" stehen.

**Comment by arbor95** [comment]
nachdem ich einen Schalter auf "nein" gesetzt habe war es nicht mehr ausgegraut.
Wieder alles auf "ja": Reiter bleibt schwarz!

**Comment by hartenthaler** [comment]
Hmm... da hatte ich etwas geändert, da es gewünscht wurde, dass der Standard in der Verwaltung von "nein" auf "ja" geändert werden soll. Muss ich noch mit einer ganz frischen Installation testen. Bei mir funktioniert es richtig.
Funktioniert es bei Dir, wenn Du alle Schalter auf "nein" setzt?

**Comment by arbor95** [comment]
Dann wird der Reiter ausgegraut.

**Comment by hartenthaler** [comment]
Wenn ich auf https://freris.de/tree/frese/individual/XI37/Theresia-Limberg gehe, dann sehe ich ihren Eintrag, aber es gibt gar keinen Reiter "Großfamilie"; wahrscheinlich weil ich nicht angemeldet bin. Auf meiner eigenen Seite ist der Reiter für Gäste freigegeben.

Wenn alle Schalter auf "nein" stehen, dann ist es korrekt, dass der Reiter ausgegraut ist. Aber wenn Du jetzt alle Schalter auf "ja" setzt (und auf SAVE drückst!), dann sollten alle Familienteile der Großfamilie angezeigt werden. Da es ja wohl nicht so ist, muss ich den Bug finden.

**Comment by arbor95** [comment]
Vielleicht hatte ich da gerade noch experimentiert. Jetz ist es so eingestellt, wie es bleiben könnte.

**Comment by arbor95** [comment]
Nur noch mal zur Info: Jetzt kann ich keinen bug mehr feststellen.

**Comment by hartenthaler** [comment]
Gut, dann ist es so wie es bei Josef und mir auch ist, aber es soll bei der erstmailgen Nutzung natürlich gleich richtig funktionieren: deshalb: sehr gut, dass Du es hier gemeldet hast.

Und jetzt sehe ich den Reiter bei Dir auch. Und korrekterweise steht bei den noch lebenden Enkelkindern "privat". Alles gut.

**Comment by hartenthaler** [comment]
when installing this module the first time, then all family parts should be enabled and in the default sequence
