### ISSUE TITLE
2.0.16.18 - Ex-partner of partner is not partner of proband

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#27]
Ex-partners (divorced/deceased) of the partner of the proband are seen in this module as a partner of the proband, but that is not correct.

![image](https://user-images.githubusercontent.com/46184729/122346434-3beecc80-cf49-11eb-989c-2658ca011ec7.png)

**Comment by hartenthaler** [comment]
This is intended. Even in the family navigator in the sidebar you can see partners of partners, too. They are members of the Extended family. But they need a label, see open issue #19

**Comment by TheDutchJewel** [comment]
Well, it is not a problem to see the ex-partner of the partner, but they are not partners of the proband and should therefore not be mentioned as such in the summary.

This one is correct:
![image](https://user-images.githubusercontent.com/46184729/122358473-f506d400-cf54-11eb-9ef9-454056827441.png)

**Comment by hartenthaler** [comment]
that is correct! will be solved together with #19
