### ISSUE TITLE
Tab Extended family - titles

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#30]
I suggest that the part h2 titles be displayed even if the part has
'%s has no ... recorded.'
otherwise the message is drowned among the others.

**Comment by hartenthaler** [comment]
This is possible. What do you think about an alternative: 

First show only those parts of the extended family which have content. Then show all the collected "... has no ... recorded" messages in one block at the end of the page without h2 titles?

**Comment by jpretired** [comment]
I would prefer to keep the order of parts as it is now, i.e. always the same. Regardless of their contents.

**Comment by hartenthaler** [comment]
this will be realized in the next release

In a future release, there will be three options in the control panel: How should empty blocks be shown?
-  always at standard location (default, as it is now implemented)
-  collect messages about empty blocks at the end
-  never

**Comment by hartenthaler** [comment]
The above-mentioned three options are now implemented in release 2.0.16.24
