### ISSUE TITLE
Request: use subject's full name instead of nickname

### ISSUE THREAD

**Issue by reteP-riS** [hartenthaler/hh_extended_family#33]
This is a nice module. Thank you, Hermann!

I nevertheless have a request. The extended family tab for an **Edward Todd LASTNAME** says "**Toddy** has 1 grandfather and 1 grandmother recorded (2 in total)." While this is factually correct I'd prefer to see his full name instead of his nickname Toddy.

**Comment by hartenthaler** [comment]
This is a tab, so you can see his full name at the top of the screen. The main idea of this module is to concentrate on the members of the extended family. When I saw the full name of the proband 9 times repeated, my opinion was to use a nice short name like the nickname or the Rufname or the first of the given names instead to show the name, but have it less dominant.

Maybe I will allow the admin to choose what he likes.

**Comment by jpretired** [comment]
If I may I agree with @hartenthaler, i.e. not full name.
But there is a tiny bug: if there is a Name prefix it shown as a name:

![image](https://user-images.githubusercontent.com/350656/122578564-48138080-d054-11eb-8935-7571115cc409.png)

**Comment by reteP-riS** [comment]
Thanks for taking care. I understand the motivation, but at least in my data the nicknames are often from the subject's childhood and sound a bit funny or even inappropriate, especially when mentioned so often on a single page. In my example I have
```
1 NAME Edward Todd* LASTNAME
2 NICK Toddy
```
Maybe use something like
"Edward Todd has ..." with Todd underlined or
"Todd has ..." or
simply remove these summary lines which only repeat what we already see in the tables with the respective colors and numbers.

**Comment by hartenthaler** [comment]
@jpretiered: yes this is a bug that has to be fixed.

@reteP-riS: ok, in the first step I will prefer Rufname as the highest priority instead of nickname; and I'm thinking about making this an option.

**Comment by hartenthaler** [comment]
- bug when there are NPFX is fixed with release 21
- Rufame is preferred more than nickname
- use option in control panel is prepared

**Comment by reteP-riS** [comment]
This is an excellent solution, Hermann. Thank you!

**Comment by hartenthaler** [comment]
done in release 2.0.16.23
