### ISSUE TITLE
Extended family save options - error

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#36]
After Control panel > Extended family > save comes an error:

Undefined index: showEmptyBlock …/modules_v4/hh_extended_family/module.php:1031
#0 …/modules_v4/hh_extended_family/module.php(1031): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/Http/RequestHandlers/ModuleAction.php(88): Hartenthaler\WebtreesModules\hh_extended_family\ExtendedFamilyTabModule->postAdminAction()
#2 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()

Full error message:
[error-extended-family-save.txt](https://github.com/hartenthaler/hh_extended_family/files/6682750/error-extended-family-save.txt)

**Comment by hartenthaler** [comment]
fixed in release 22
