### ISSUE TITLE
Man's male partner

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#43]
Please take a look at a person
https://www.jprodina.cz/tree/nase-rodina/individual/I3698/Jan-Placek#tab-_hh_extended_family_

Here Jan married his wife Magdalena as a widow of Vavřinec Opletal.
It looks strange that Vavřinec is a male partner of Jan.
As to me Vavřinec should not be mentioned here as a partner of Jan.

**Comment by hartenthaler** [comment]
This is intended. Even in the family navigator in the sidebar you can see partners of partners, too. They are members of the Extended family. I do not plan at the moment to check live dates (like death, marriage or divorce dates) to decide who lived at the same time together or not. In a modern patchwork family it is possible that three or more persons are living together as partners. It is the idea of my module to show that there is a group of potential partners and partners of partners.

Please see #34 and #27, too. Maybe the situation would be less confusiong if there is a label that Vavřinec was the partner of Magdalena; this is planned, see open issue #19 and #9.
