### ISSUE TITLE
Wrong lists of children and grandchildren

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#45]
Please take a look at this person's extended family in my family tree:
https://www.jprodina.cz/tree/nase-rodina/individual/I261/Rajmund-Spunda#tab-_hh_extended_family_

The lists of children and grandchildren are doubled (on left and right side the same data).
Their counts are correct but only count minus one are listed.

What is special with this person is that he married a widow with 2 children from her first marriage.

**Comment by hartenthaler** [comment]
I observed the same in one family of my relatives. I have to check this.

**Comment by hartenthaler** [comment]
bug found and fixed
