### ISSUE TITLE
Czech translation updated

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#50]
Please replace the function czechTranslations() with new version in the attached file:
[Czech-translation.txt](https://github.com/hartenthaler/hh_extended_family/files/6834847/Czech-translation.txt)
It contains the new strings as to compact design, parents-in-law and some minor amendments.
Thank you.

**Comment by hartenthaler** [comment]
Thank you! Included in release 2.0.16.30.
