### ISSUE TITLE
Partners section: difference between partners and ex-partners is no longer visible

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#51]
The partners section has become unusable because the distinction between partners and exparters is now also visually dropped.

In version 2.0.16.18 (see [issue #27](https://github.com/hartenthaler/hh_extended_family/issues/27)), only the textual indication of ex-partners was wrong, but visually it was clear:
![afbeelding](https://user-images.githubusercontent.com/46184729/126058331-f6421f0f-7705-4fe9-8e9d-67d7e22531e3.png)

In version 2.0.16.30 (and probably earlier) the visual distinction is now also dropped:
![afbeelding](https://user-images.githubusercontent.com/46184729/126058555-a9fbdc1a-52ab-4bad-8dbb-f797f9ac805e.png)

**Comment by hartenthaler** [comment]
Yes, you are right. I'm working on that. This is already a topic of issue #19

**Comment by hartenthaler** [comment]
fixed in release 2.0.16.31
