### ISSUE TITLE
Check parents-in-law of traductions

### ISSUE THREAD

**Issue by yako1984** [hartenthaler/hh_extended_family#52]
In this line to get the translation I had to go from putting in the original line: "parents-in-law" to: "parents_in_law"
with low bar _. In the rest of the languages ​​it is with guinoes and not with a low bar, it is a good idea to see if in the other translations it also fails.

'%s has no parents_in_law recorded.' => '%s no tiene Suegros registrados.', // Bugfix change parents-in-law for parents_in_law

Un slaudo!

**Comment by hartenthaler** [comment]
This was a bug for all languages. Thank you for reporting! It is fixed now, so you can change back your bugfix in the next release.
