### ISSUE TITLE
 Text too large. Seems <h> tag error

### ISSUE THREAD

**Issue by yako1984** [hartenthaler/hh_extended_family#54]
![Screenshot_2](https://user-images.githubusercontent.com/67491705/126067397-a4a99127-ca49-43fe-bd2c-098ae24a49d1.jpg)

**Comment by hartenthaler** [comment]
I can see the problem, but cannot reproduce this. Maybe it is fixed with the next release (coming later today).

**Comment by yako1984** [comment]
Fixed, the error was mine, I had the module without renaming to: Rename the folder to hh_extended_family
Once renamed it works perfect
