### ISSUE TITLE
Individuals with unknown sex not indicated clearly

### ISSUE THREAD

**Issue by reteP-riS** [hartenthaler/hh_extended_family#57]
I have an exceptional situation where for one uncle or aunt I don't know the sex. In the "Uncles and Aunts" section the calculation result is therefore 3+6=10:

"B. has 3 uncles and 6 aunts recorded (10 in total)."

Any idea how to resolve this issue which might occur in other sections as well?

**Comment by hartenthaler** [comment]
To indicate this situation I added „ in total“. 3 +6 and in total 10 indicates that there is another person which is not Uncle and not Aunt, but is counted for the total number. Would you prefer to make this explicitly? Can you suggest a sentence, please?

Viele Grüße
Hermann
---

**Comment by reteP-riS** [comment]
If possible I'd replace the existing phrase

"... has 3 uncles and 6 aunts recorded (10 in total)."

with

"... has 3 uncles, 6 aunts and 1 individual with unknown sex recorded (10 in total)."

I *believe* this method can be applied to all sections.

**Comment by hartenthaler** [comment]
Yes.

**Comment by hartenthaler** [comment]
There are the following 4 types of combinations of M/MM=one male/many males, F/FF=one female/many females, and U/UU=one with unknown sex/many with unknown sex:
- M or F or O
- "only M/MM" or "only F/FF" or "only U/UU"
-  "only M/MM and F/FF" or "only M/MM and U/UU" or "only F/FF and U/UU"
- "M/MM and F/FF and U/UU".

Examples for the family part "children" are:
- ... has one son.
- ... has 3 daughters.
- ... has 1 son and 2 daughters (3 in total).
- ... has 1 son, 2 daughters, and 3 children of unknown sex (6 in total).

This results in many combinations which have to be translated. And this has to be repeated for all the extended family parts. And for all languages. Sorry for the lot of work for the translators.

This feature will be part of the next release (at least in German and English).

**Comment by hartenthaler** [comment]
implemented in release 2.0.16.56

**Comment by reteP-riS** [comment]
Thanks for all the good work, Hermann! With release 2.0.16.56 I can see now the revised phrases, e. g.

**Uncles and Aunts:**
B. has 4 uncles, 6 aunts, and _2 uncles or aunts of unknown sex recorded_ (12 in total).

**Uncles and Aunts by marriage:**
B. has 2 uncles by marriage, 1 aunt by marriage, and _1 uncle or aunt by marriage of unknown sex recorded_ (4 in total).

The first one for Uncles and Aunts translates well into German, but the second one for **Uncles and Aunts by marriage** doesn't translate into German at all.

I understand the creation of these phrases is rather complex and translation even more so. Thanks again!

**Comment by hartenthaler** [comment]
Oh! Just before I released the new version I merged a pull request with dutch translations. On this step, I lost the last translations I had made before. Sorry! Will be fixed in the next release.

**Comment by hartenthaler** [comment]
now they are part of release 2.0.16.57

**Comment by reteP-riS** [comment]
Thank you, Hermann!

One more request (sorry, I should have mentioned that earlier): would it be possible to put a thin dashed border around the box of an individual with unknown sex like the one on the facts and events tab (in the webtrees default theme).

**Comment by hartenthaler** [comment]
... just added a line in the css file. Will be fixed in the next release.
