### ISSUE TITLE
position and height of labels

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#71]
The vertical position and height of the stickers don't fit between the horizontal field edges.

**webtrees theme:**
![afbeelding](https://user-images.githubusercontent.com/46184729/127274912-0b4e78be-9d54-4801-b91a-134a559ba22c.png)

**Rural theme:**
![afbeelding](https://user-images.githubusercontent.com/46184729/127275031-201c8cde-97ca-4d15-b3cd-6d3c0828e23f.png)

**Comment by TheDutchJewel** [comment]
In the Parents and Siblings sections, the stickers are not properly aligned horizontally:
![afbeelding](https://user-images.githubusercontent.com/46184729/127293977-8bff911e-1fc8-4dce-97bc-e353f4fc2087.png)

**Comment by hartenthaler** [comment]
fixed in release 2.0.16.38, maybe not perfect but the best I could offer (I need help to make the distance at the bottom of the label a bit greater)

**Comment by TheDutchJewel** [comment]
With this two changes, the **compact mode** looks fine to me:

#hh_extended_family_content .wt-chart-box-m,
#hh_extended_family_content .wt-chart-box-f,
#hh_extended_family_content .wt-chart-box-u {
    clear: left;
    **display: flex;
    align-items: center;**
    float: left;
    border-radius: 5px;
    margin: 2px 0;
    width: 99%;
}

.hh_extended_family_lifespan {
    font-size: 10px;
    padding: 3px 5px **0px** 5px;
}

![afbeelding](https://user-images.githubusercontent.com/46184729/127348909-e0fd56ed-c11c-43f0-aacb-7c6bdd64fd1d.png)

But this effect the **enriched mode**. This can be solved by using a separate css code for the compact mode and for the enriched mode.

**Comment by hartenthaler** [comment]
Thank you for your help! The next release will use your idea. There are new CSS classes for enriched and compact styles defined.
