### ISSUE TITLE
2.0.6.43 - Untranslated string: '%s has no co-parents-in-law recorded.'

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#76]
In version 2.0.6.43 is a new section added with one untranslated string:
`'%s has no co-parents-in-law recorded.'`

![afbeelding](https://user-images.githubusercontent.com/46184729/128138817-6db77b1b-f007-4185-b015-3b80f93cb7ce.png)

**Comment by hartenthaler** [comment]
fixed in next release
