### ISSUE TITLE
Group 'co-parents-in-law of stepchildren' by marriage of the children

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#80]
The **co-parents-in-law of biological children** are grouped by marriage of the children, but with the **co-parents-in-law of stepchildren** this does not happen:

![afbeelding](https://user-images.githubusercontent.com/46184729/128302042-aeadf79b-16b5-4091-8ec1-b525acdcbb28.png)

**Comment by hartenthaler** [comment]
fixed in release 2.0.16.44
