### ISSUE TITLE
'1 ASSO' vs '2 _ASSO'

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#91]
The Extended family module uses the `1 ASSO @I123@\n2 RELA triplet` tag for labels.

But when I use this, the custom relation is not translated. Check this webtrees issue [#3848](https://github.com/fisharebest/webtrees/issues/3848#issuecomment-835869891-permalink) for the solution.

The solution is:
1. change `1 ASSO @I123@\n2 RELA triplet` into `2 _ASSO @I123@\n3 RELA triplet` and replace it to a `1` tag, like `1 BIRT`;
2. modify https://github.com/fisharebest/webtrees/blob/main/app/Elements/RelationIsDescriptor.php to add the translation source strings;
3. adapt an [example module](https://github.com/webtrees/example-module) as translation module and add the source and destination translation strings.

This works fine, but now the Extended family module doesn't show the labels anymore.

Is it possible to fix this?

**Comment by hartenthaler** [comment]
Both possibilities to indicate twins/triplets/... are now implemented and will be available in release 2.0.16.49.
