### ISSUE TITLE
make language parts to be an individual file?

### ISSUE THREAD

**Issue by dust2k** [hartenthaler/hh_extended_family#93]
Can we make the other language translation to be an individual file (Json/ini/csv) instead of part of php file? I would like to contribute on Simplified and Tranditional Chinese language translation but found it's hard to adding these two parts into php file because I need read code carefully to make sure new translation won't make code broken.

**Comment by hartenthaler** [comment]
This is great that you intend to translate this module into the Chinese language! What are the language codes: zh (traditional) and zh_CN (simplified)?

I just separated the translation part from the other PHP code (it will be part of the next release of this module). Maybe you can download just this file https://github.com/hartenthaler/hh_extended_family/blob/main/resources/lang/ExtendedFamilyTranslations.php

You can send it back to me here after you added your translations, or you can do it using a pull request.

Use the German translation as an example for your copy and paste, please. This part is always complete. As far as I know, the Chinese language follows the same plural rule as the Vietnamese language (no special plural forms), so maybe the Vietnamese translation part can be a good example of how to define the plural forms.

But it is also ok for me if you send me a csv or txt file.

**Comment by dust2k** [comment]
Thanks for spliting the language file, I am working on translation now, language code should be either zh-HANS and zh-HANT or zh_CN and zh_TW, I don't know which one is Webtree using.

I took German translation as the template for translating, might take a little while and I will send back to you once I've done it.

**Comment by hartenthaler** [comment]
I just checked it: webtrees uses "zh-Hans" and "zh-Hant"

**Comment by hartenthaler** [comment]
I tested Chinese translations. It is prepared in the just-published release 2.0.16.50, so that you should be able to see the translations you have already done.
