### ISSUE TITLE
Request: labels for STILLBORN and INFANT 

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#94]
The labels are very informative.

Is it possible to also add labels for **STILLBORN** (`2 AGE / STILLBORN`) and **INFANT** (`2 AGE / INFANT`)?

**Comment by hartenthaler** [comment]
this will be part of next release

**Comment by TheDutchJewel** [comment]
I don't see these labels in the new version.

Not in the Extended family tab of the parents, siblings etc.

Am I overlooking something?

**Comment by TheDutchJewel** [comment]
By the way, in the [readme](https://github.com/hartenthaler/hh_extended_family/blob/main/readme.md#user-content-description) you wrote:

> is stillborn or died as an infant, should look like "1 BIRT\n2 AGE STILLBORN" or "1 DEAT\n2 AGE INFANT"

But in the [GEDCOM 5.5.1 Specifications](https://gedcom.io/specifications/ged551.pdf) at page 68 I see **both** values are used with the **DEAT** fact:

> Codes in Event Date:
> In this version of GEDCOM, the information has been removed from the date value and specified by an <AGE_AT_EVENT> key word value which indicates a descriptive age value at the time of the enclosing event. (See <AGE_AT_EVENT>, page 42.) For example:
> 1 DEAT
> 2 DATE 13 MAY 1984
> 2 AGE STILLBORN
> meaning this person died at age approximately 0 days
> 1 DEAT
> 2 DATE 13 MAY 1984
> 2 AGE INFANT
> meaning this person died at age less than 1 year old.

**Comment by hartenthaler** [comment]
These examples are together with DEAT and this makes sense, but the definition allows AGE STILLBORN und AGE INFANT (or AGE CHILD) to be used with all INDI events, like birth, baptism, ...
```
INDIVIDUAL_EVENT_DETAIL:=
n <<EVENT_DETAIL>>
n AGE <AGE_AT_EVENT>
```
and even with family events like marriage. My module supports labels only for
- 1 BIRT | ... | 2 AGE STILLBORN
- 1 DEAT | ... | 2 AGE STILLBORN
- 1 DEAT | ... | 2 AGE INFANT

![Screenshot (465)_LI](https://user-images.githubusercontent.com/6324175/133159168-473ed05c-944a-4068-affd-bc6cfe980b1e.jpg)

**Comment by TheDutchJewel** [comment]
Thanks for the clarification.

I had to remove the old version to get the new one working. See [issue #102](https://github.com/hartenthaler/hh_extended_family/issues/102).
