### ISSUE TITLE
Translation for label "challenged" missing

### ISSUE THREAD

**Issue by reteP-riS** [hartenthaler/hh_extended_family#96]
I have several child relationships that are being challenged. There are documented GEDCOM 5.5.1 compliant as

1 FAMC @F1@
2 PEDI challenged

The respective label is in green letters and says "challenged" in all languages I tested. Are the translations simply missing or did you intentionally leave them out? I'd prefer the translation. As there are only three different options, i. e. PEDI [challenged | disproven | proven] that should be possible.

**Comment by hartenthaler** [comment]
I never used or have seen these three values. The translations are simply missing.

**Comment by hartenthaler** [comment]
GEDCOM 5.5.1 says:

```
CHILD_TO_FAMILY_LINK:=
n FAMC @<XREF:FAM>@ 
+1 PEDI <PEDIGREE_LINKAGE_TYPE>
+1 STAT <CHILD_LINKAGE_STATUS> 
```
So your code
```
1 FAMC @F1@
2 PEDI challenged
```
is not compliant. It should look like
```
1 FAMC @F1@
2 PEDI birth
2 STAT challenged
```

**Comment by hartenthaler** [comment]
Labels for "2 STAT challenged", "2 STAT disproven" and "2 STAT proven" will be part of the next release.

**Comment by reteP-riS** [comment]
Thank you, Hermann! My bad.
