### ISSUE TITLE
It does not separate the nephews on the husband's side, on the father's side.

### ISSUE THREAD

**Issue by yako1984** [hartenthaler/hh_extended_family#97]
It does not separate the nephews on the husband's side, on the father's side. In exchange for the nephews of her siblings, she separates them either by father or mother.

![bug](https://user-images.githubusercontent.com/67491705/132951964-9894a071-9cbe-4603-a1d7-9206651923c1.png)

**Comment by hartenthaler** [comment]
yes, this is a bug

**Comment by hartenthaler** [comment]
fixed in release 2.0.16.50
